---
apiVersion: v1
kind: Secret
metadata:
  name: qevent
type: Opaque
data:
  RABBIT_MQ_USERNAME: cWV2ZW50LWs4Cg==
  RABBIT_MQ_PASSWORD: MTIzNDU2Cg==
  APIKEY: ZWgxMjM0LWRzZHMtNDMzMjUtODVmYS02YWdkZzMxMgo=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: qevent
  labels:
    app: qevent
data:
  SERVER_PORT: "8084"
  MONGODB_URI: "mongodb://event-mongodb:27017/qagile"
  MONGODB_STATUS_HOST: event-mongodb
  MONGODB_STATUS_PORT: "28017"
  URL_QUSER: http://35.170.82.157:30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: event-app
  name: event-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-app
  template:
    metadata:
      labels:
        app: event-app
    spec:
      containers:
      - name: event-app
        image: qagile/qevent:0.0.182
        ports:
        - containerPort: 8084
        env:
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: qevent
              key: SERVER_PORT
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: qevent
              key: MONGODB_URI
        - name: MONGODB_STATUS_HOST         
          valueFrom:
            configMapKeyRef:
              name: qevent
              key: MONGODB_STATUS_HOST
        - name: MONGODB_STATUS_PORT
          valueFrom:
            configMapKeyRef:
              name: qevent
              key: MONGODB_STATUS_PORT
        - name: URL_QUSER
          valueFrom:
            configMapKeyRef:
              name: qevent
              key: URL_QUSER
        - name: RABBIT_MQ_HOST
          value: ec2-15-228-10-244.sa-east-1.compute.amazonaws.com
        - name: RABBIT_MQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: qevent
              key: RABBIT_MQ_USERNAME
        - name: RABBIT_MQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: qevent
              key: RABBIT_MQ_PASSWORD
        - name: APIKEY
          valueFrom:
            secretKeyRef:
              name: qevent
              key: APIKEY
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: event-app
spec:
  type: NodePort
  selector:
    app: event-app
  ports:
    - protocol: TCP
      port: 84
      targetPort: 8084
      nodePort: 30084
